//
//  EidReader.mm
//  react-native-eid-reader
//
//  Codegen-driven TurboModule (New Architecture). The public surface is
//  declared in `src/NativeEIdReader.ts`; the Codegen step generates the
//  `NativeEIdReaderSpec` protocol that this class conforms to. All real
//  work is delegated to the `EIdReaderImpl` Swift class.
//
//  Previously this file used the legacy `RCT_EXTERN_MODULE` / `RCT_EXTERN_METHOD`
//  macros. Under the New Architecture those are replaced by ordinary
//  Objective-C method implementations that match the signatures in the
//  generated `NativeEIdReaderSpec` protocol.
//

#import "EidReader.h"

// Bridging header generated by Xcode exposes the Swift `EIdReaderImpl` class
// to Objective-C. The host app's Pods integration generates a
// `<target>-Swift.h` header at build time; including it here lets us call
// the Swift impl directly.
#if __has_include("react_native_eid_reader-Swift.h")
#import "react_native_eid_reader-Swift.h"
#elif __has_include(<react_native_eid_reader/react_native_eid_reader-Swift.h>)
#import <react_native_eid_reader/react_native_eid_reader-Swift.h>
#endif

@interface EIdReader ()
@property (nonatomic, strong) EIdReaderImpl *impl;
@end

@implementation EIdReader

RCT_EXPORT_MODULE()

+ (BOOL)requiresMainQueueSetup
{
  return NO;
}

- (instancetype)init
{
  if ((self = [super init])) {
    _impl = [[EIdReaderImpl alloc] init];
  }
  return self;
}

#pragma mark - NativeEIdReaderSpec

- (void)isNfcSupported:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject
{
  [_impl isNfcSupportedWithResolver:resolve withRejecter:reject];
}

- (void)isNfcEnabled:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject
{
  [_impl isNfcEnabledWithResolver:resolve withRejecter:reject];
}

- (void)openNfcSettings:(RCTPromiseResolveBlock)resolve
                 reject:(RCTPromiseRejectBlock)reject
{
  [_impl openNfcSettingsWithResolver:resolve withRejecter:reject];
}

- (void)startReading:(JS::NativeEIdReader::StartReadingParams &)params
             resolve:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject
{
  // The generated spec materialises the typed-object parameter as a C++ value
  // type. Convert it into an `NSDictionary *` matching the shape the Swift
  // implementation already expects, so the Swift code stays unchanged.
  NSMutableDictionary *dict = [NSMutableDictionary new];

  auto mrz = params.mrzInfo();
  dict[@"mrzInfo"] = @{
    @"expirationDate": @(mrz.expirationDate().UTF8String ?: ""),
    @"birthDate":      @(mrz.birthDate().UTF8String ?: ""),
    @"documentNumber": @(mrz.documentNumber().UTF8String ?: ""),
  };

  if (auto includeImages = params.includeImages()) {
    dict[@"includeImages"] = @(*includeImages);
  }
  if (auto includeRawData = params.includeRawData()) {
    dict[@"includeRawData"] = @(*includeRawData);
  }
  if (auto labels = params.labels()) {
    NSMutableDictionary *labelsDict = [NSMutableDictionary new];
    #define COPY_LABEL(key) \
      if (auto v = labels->key()) { labelsDict[@#key] = @(v.UTF8String ?: ""); }
    COPY_LABEL(title)
    COPY_LABEL(cancelButton)
    COPY_LABEL(requestPresentPassport)
    COPY_LABEL(authenticatingWithPassport)
    COPY_LABEL(reading)
    COPY_LABEL(activeAuthentication)
    COPY_LABEL(successfulRead)
    COPY_LABEL(tagNotValid)
    COPY_LABEL(moreThanOneTagFound)
    COPY_LABEL(invalidMRZKey)
    COPY_LABEL(error)
    #undef COPY_LABEL
    dict[@"labels"] = labelsDict;
  }

  [_impl startReading:dict withResolver:resolve withRejecter:reject];
}

- (void)stopReading
{
  [_impl stopReading];
}

- (NSString *)imageDataUrlToJpegDataUrl:(NSString *)dataUrl
{
  return [_impl imageDataUrlToJpegDataUrl:dataUrl] ?: @"";
}

#pragma mark - NativeEventEmitter lifecycle

- (void)addListener:(NSString *)eventName
{
  // no-op: events are not emitted from the iOS side of this module.
}

- (void)removeListeners:(double)count
{
  // no-op
}

#pragma mark - TurboModule registration

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeEIdReaderSpecJSI>(params);
}

@end
